/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.systec.view;

/**
 *
 * @author maq19
 */
public class Frm2_Principal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public Frm2_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        btnVenda = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnAjudar = new javax.swing.JButton();
        btnConfiguracao = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jMenuItem7.setText("jMenuItem7");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delicious bread | ver. 1.0.0");
        setExtendedState(6);
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/Login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(630, 200, 240, 320);

        jPanelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        jPanelMenu.setLayout(null);

        btnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Shopping_Cart_80px.png"))); // NOI18N
        btnVenda.setToolTipText("Efetuar Venda");
        jPanelMenu.add(btnVenda);
        btnVenda.setBounds(20, 30, 80, 70);

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Add_User_Male_80px.png"))); // NOI18N
        btnUsuario.setToolTipText("Casdatro Usuário");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jPanelMenu.add(btnUsuario);
        btnUsuario.setBounds(20, 120, 80, 80);

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Team_80px.png"))); // NOI18N
        btnCliente.setToolTipText("Cadastro Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanelMenu.add(btnCliente);
        btnCliente.setBounds(20, 230, 80, 70);

        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Add_Shopping_Cart_80px.png"))); // NOI18N
        btnProduto.setToolTipText("Add Produtos");
        jPanelMenu.add(btnProduto);
        btnProduto.setBounds(20, 330, 80, 70);

        btnAjudar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Help_80px.png"))); // NOI18N
        btnAjudar.setToolTipText("Ajuda");
        jPanelMenu.add(btnAjudar);
        btnAjudar.setBounds(20, 420, 80, 70);

        btnConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Work_80px_1.png"))); // NOI18N
        btnConfiguracao.setToolTipText("Configuração");
        jPanelMenu.add(btnConfiguracao);
        btnConfiguracao.setBounds(20, 520, 80, 70);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Exit_80px.png"))); // NOI18N
        btnSair.setToolTipText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanelMenu.add(btnSair);
        btnSair.setBounds(20, 610, 80, 80);

        getContentPane().add(jPanelMenu);
        jPanelMenu.setBounds(0, 0, 120, 700);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 0));
        jLabel2.setText("Delicious bread");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(580, 510, 290, 50);

        setSize(new java.awt.Dimension(1116, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        Frm2_Usuario usuario = new Frm2_Usuario(this, true);
        usuario.setVisible(true);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        Frm5_CadasCliente cliente = new Frm5_CadasCliente();
        cliente.setVisible(true);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
        Frm1_Login login = new Frm1_Login();
        login.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm2_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm2_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjudar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnConfiguracao;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
