/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.systec.view;

import com.systec.model.CadasCliente;
import com.systec.model.dao.CadasClienteDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Steve Wallef
 */
public class Frm5_CadasCliente extends javax.swing.JFrame {

    /**
     * Creates new form Frm5_CadasProduto
     */
    public Frm5_CadasCliente() {
        initComponents();

    }
    public static int linha = -1;
    int flang = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        btnExclui = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        btnAltera = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 90, 49, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("CPF");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 150, 30, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Telefone");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 210, 67, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 50, 18, 25);

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.setText("XXXX");
        jPanel1.add(txtID);
        txtID.setBounds(50, 50, 50, 20);

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setEnabled(false);
        jPanel1.add(txtNome);
        txtNome.setBounds(10, 120, 480, 30);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setEnabled(false);
        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtTelefone);
        txtTelefone.setBounds(10, 240, 140, 30);

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setEnabled(false);
        txtCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtCpf);
        txtCpf.setBounds(10, 180, 140, 30);

        btnExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Cancel_50px.png"))); // NOI18N
        btnExclui.setToolTipText("Exclui");
        btnExclui.setEnabled(false);
        btnExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiActionPerformed(evt);
            }
        });
        jPanel1.add(btnExclui);
        btnExclui.setBounds(430, 310, 50, 50);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Plus_50px.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo);
        btnNovo.setBounds(20, 310, 50, 50);

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Search_Property_50px.png"))); // NOI18N
        btnPesquisa.setToolTipText("Pesquisa");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisa);
        btnPesquisa.setBounds(100, 310, 50, 50);

        btnSalva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Ok_50px.png"))); // NOI18N
        btnSalva.setToolTipText("Salva");
        btnSalva.setEnabled(false);
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalva);
        btnSalva.setBounds(180, 310, 50, 50);

        btnAltera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/iconEditar.png"))); // NOI18N
        btnAltera.setToolTipText("Altera");
        btnAltera.setEnabled(false);
        btnAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraActionPerformed(evt);
            }
        });
        jPanel1.add(btnAltera);
        btnAltera.setBounds(260, 310, 50, 50);

        btnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Minus_50px.png"))); // NOI18N
        btnCancela.setToolTipText("Cancela");
        btnCancela.setEnabled(false);
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancela);
        btnCancela.setBounds(340, 310, 50, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 370);

        setSize(new java.awt.Dimension(516, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        //Controle de Tela
        txtNome.setEnabled(true);
        txtCpf.setEnabled(true);
        txtTelefone.setEnabled(true);

        //Controle de Botões
        btnSalva.setEnabled(true);
        btnPesquisa.setEnabled(false);
        btnNovo.setEnabled(false);
        btnAltera.setEnabled(false);
        btnCancela.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed

        if (!txtNome.getText().isEmpty() && !txtCpf.getText().equals("   .   .   -  ") && !txtTelefone.equals("(  )     -   ")) {

            if (txtCpf.getText().length() != 14) {

                JOptionPane.showMessageDialog(this, "CPF Incompleto......");

            } else {

                CadasClienteDAO cli = new CadasClienteDAO();
                CadasCliente cad = new CadasCliente(txtNome.getText(), txtCpf.getText(), txtTelefone.getText());
                int salva = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja salvar?", "Atenção", JOptionPane.YES_NO_OPTION);
                if (salva == JOptionPane.YES_OPTION) {
                    if (cli.inserir(cad)) {
                        JOptionPane.showMessageDialog(this, "Cliente Salvo com sucesso!");

                        //Controle de Tela
                        txtNome.setText("");
                        txtCpf.setText("");
                        txtTelefone.setText("");

                        txtNome.setEnabled(false);
                        txtCpf.setEnabled(false);
                        txtTelefone.setEnabled(false);

                        //Controle de Botões
                        btnSalva.setEnabled(false);
                        btnPesquisa.setEnabled(true);
                        btnNovo.setEnabled(true);
                        btnAltera.setEnabled(false);

                    }

                } 
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por Favor Preencha Todos os Campos");
        }


    }//GEN-LAST:event_btnSalvaActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        CadasCliente usu = new CadasCliente();
        CadasClienteDAO cli = new CadasClienteDAO();
        flang = 2;
        //Chamando tela para realização da pesquisa.
        Frm6_PesqCliente pesqCli = new Frm6_PesqCliente(null, true);
        pesqCli.setVisible(true);

        if (linha >= 0) {

            btnExclui.setEnabled(true);

            cli.pesquisar(CadasClienteDAO.getId_cliente());

            //Controle de Tela
            txtNome.setEnabled(true);
            txtCpf.setEnabled(true);
            txtTelefone.setEnabled(true);

            //Controle de Botões
            btnSalva.setEnabled(false);
            btnPesquisa.setEnabled(false);
            btnNovo.setEnabled(false);
            btnCancela.setEnabled(true);
            btnAltera.setEnabled(true);

            // Setando campos com seus respectivos valores.
            txtID.setText(Integer.toString(CadasCliente.getId_cliente()));
            txtNome.setText((CadasCliente.getNome()));
            txtCpf.setText((CadasCliente.getCpf()));
            txtTelefone.setText((CadasCliente.getTelefone()));

        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraActionPerformed

        CadasClienteDAO dao = new CadasClienteDAO();
        CadasCliente cad = new CadasCliente(Integer.parseInt(txtID.getText()), txtNome.getText(), txtCpf.getText(), txtTelefone.getText());
        int altera = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja alterar?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (altera == JOptionPane.YES_OPTION) {
            if (dao.alterar(cad)) {
                JOptionPane.showMessageDialog(this, "Alteração de Cliente Salva com sucesso!");

                //Controle de Tela
                txtID.setText("XXXX");
                txtNome.setText("");
                txtCpf.setText("");
                txtTelefone.setText("");

                txtNome.setEnabled(false);
                txtCpf.setEnabled(false);
                txtTelefone.setEnabled(false);

                //Controle de Botões
                btnSalva.setEnabled(false);
                btnPesquisa.setEnabled(true);
                btnNovo.setEnabled(true);
                btnAltera.setEnabled(false);
                btnExclui.setEnabled(false);
                btnCancela.setEnabled(false);
            }

        } 

    }//GEN-LAST:event_btnAlteraActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        //Controle de Tela

        txtNome.setText("");
        txtCpf.setText("");
        txtTelefone.setText("");
        txtID.setText("XXXX");

        txtNome.setEnabled(false);
        txtCpf.setEnabled(false);
        txtTelefone.setEnabled(false);

        //Controle de Botões
        btnSalva.setEnabled(false);
        btnPesquisa.setEnabled(true);
        btnNovo.setEnabled(true);
        btnCancela.setEnabled(false);
        btnExclui.setEnabled(false);
        btnAltera.setEnabled(false);
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void btnExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiActionPerformed
        CadasClienteDAO dao = new CadasClienteDAO();
        int apagado = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (apagado == JOptionPane.YES_OPTION) {
            if (dao.deletar(dao)) {
                JOptionPane.showMessageDialog(this, "Usuário Apagada com sucesso!");
                //Controle de Tela
                txtID.setText("XXXX");
                txtNome.setText("");
                txtCpf.setText("");
                txtTelefone.setText("");

                txtNome.setEnabled(false);
                txtCpf.setEnabled(false);
                txtTelefone.setEnabled(false);

                //Controle de Botões
                btnSalva.setEnabled(false);
                btnPesquisa.setEnabled(true);
                btnNovo.setEnabled(true);
                btnCancela.setEnabled(false);
                btnExclui.setEnabled(false);
                btnAltera.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnExcluiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm5_CadasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm5_CadasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm5_CadasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm5_CadasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm5_CadasCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltera;
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnExclui;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
