/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.systec.view;

import com.systec.model.CadasProduto;
import com.systec.model.dao.CadasProdutoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Steve Wallef
 */
public class Frm8_CadasProduto extends javax.swing.JFrame {

    /**
     * Creates new form Frm8_CadasProduto
     */
    public Frm8_CadasProduto() {
        initComponents();
    }
    public static int linha = -1;
    int flang = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        btnAltera = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        btnExclui = new javax.swing.JButton();
        txtValor = new javax.swing.JFormattedTextField();
        txtQtd = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadasdatro Produto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("ID");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.setText("XXXX");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nome");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Valor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Quantidade");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Plus_50px.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Search_Property_50px.png"))); // NOI18N
        btnPesquisa.setToolTipText("Pesquisa");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        btnSalva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Ok_50px.png"))); // NOI18N
        btnSalva.setToolTipText("Salva");
        btnSalva.setEnabled(false);
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        btnAltera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/iconEditar.png"))); // NOI18N
        btnAltera.setToolTipText("Altera");
        btnAltera.setEnabled(false);
        btnAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraActionPerformed(evt);
            }
        });

        btnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Minus_50px.png"))); // NOI18N
        btnCancela.setToolTipText("Cancela");
        btnCancela.setEnabled(false);
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        btnExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Cancel_50px.png"))); // NOI18N
        btnExclui.setToolTipText("Exclui");
        btnExclui.setEnabled(false);
        btnExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiActionPerformed(evt);
            }
        });

        try {
            txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtValor.setEnabled(false);
        txtValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        try {
            txtQtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtQtd.setEnabled(false);
        txtQtd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(txtQtd))
                .addContainerGap(432, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(22, 22, 22)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnAltera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btnExclui, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 35, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(txtID))
                    .addGap(15, 15, 15)
                    .addComponent(jLabel1)
                    .addGap(5, 5, 5)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2)
                    .addGap(45, 45, 45)
                    .addComponent(jLabel3)
                    .addGap(45, 45, 45)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAltera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExclui, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 31, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(555, 432));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        //Controle de Tela
        txtNome.setEnabled(true);
        txtValor.setEnabled(true);
        txtQtd.setEnabled(true);

        //Controle de Botões
        btnSalva.setEnabled(true);
        btnPesquisa.setEnabled(false);
        btnNovo.setEnabled(false);
        btnAltera.setEnabled(false);
        btnCancela.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        CadasProduto usu = new CadasProduto();
        CadasProdutoDAO cli = new CadasProdutoDAO();
        flang = 2;
        //Chamando tela para realização da pesquisa.
        Frm7_PesqProduto pesqProd = new Frm7_PesqProduto(null, true);
        pesqProd.setVisible(true);

        if (linha >= 0) {

            btnExclui.setEnabled(true);

            cli.pesquisar(CadasProdutoDAO.getId_produtos());

            //Controle de Tela
            txtNome.setEnabled(true);
            txtValor.setEnabled(true);
            txtQtd.setEnabled(true);

            //Controle de Botões
            btnSalva.setEnabled(false);
            btnPesquisa.setEnabled(false);
            btnNovo.setEnabled(false);
            btnCancela.setEnabled(true);
            btnAltera.setEnabled(true);

            // Setando campos com seus respectivos valores.
            txtID.setText(Integer.toString(CadasProduto.getId_produtos()));
            txtNome.setText((CadasProduto.getNome()));
            txtValor.setText((CadasProduto.getValor()));
            txtQtd.setText((CadasProduto.getQtd()));

        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed

        if (!txtNome.getText().isEmpty() && !txtValor.getText().equals("  .  ") && !txtQtd.equals("  .  ")) {

            CadasProdutoDAO pro = new CadasProdutoDAO();
            CadasProduto cad = new CadasProduto(txtNome.getText(),txtValor.getText(),txtQtd.getText());
            int salva = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja salvar?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (salva == JOptionPane.YES_OPTION) {
                if (pro.inserir(cad)) {
                    JOptionPane.showMessageDialog(this, "Produto Salvo com sucesso!");

                    //Controle de Tela
                    txtNome.setText("");
                    txtValor.setText("");
                    txtQtd.setText("");

                    txtNome.setEnabled(false);
                    txtValor.setEnabled(false);
                    txtQtd.setEnabled(false);

                    //Controle de Botões
                    btnSalva.setEnabled(false);
                    btnPesquisa.setEnabled(true);
                    btnCancela.setEnabled(false);
                    btnNovo.setEnabled(true);
                    btnAltera.setEnabled(false);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Por Favor Preencha Todos os Campos");
            }
        }
    }//GEN-LAST:event_btnSalvaActionPerformed

    private void btnAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraActionPerformed

        CadasProdutoDAO dao = new CadasProdutoDAO();
        CadasProduto cad = new CadasProduto(Integer.parseInt(txtID.getText()), txtNome.getText(), txtValor.getText(), txtQtd.getText());
        int altera = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja alterar?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (altera == JOptionPane.YES_OPTION) {
            if (dao.alterar(cad)) {
                JOptionPane.showMessageDialog(this, "Alteração de Produto Salva com sucesso!");

                //Controle de Tela
                txtID.setText("XXXX");
                txtNome.setText("");
                txtValor.setText("");
                txtQtd.setText("");

                txtNome.setEnabled(false);
                txtValor.setEnabled(false);
                txtQtd.setEnabled(false);

                //Controle de Botões
                btnSalva.setEnabled(false);
                btnPesquisa.setEnabled(true);
                btnNovo.setEnabled(true);
                btnAltera.setEnabled(false);
                btnExclui.setEnabled(false);
                btnCancela.setEnabled(false);
            }

        }
    }//GEN-LAST:event_btnAlteraActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        //Controle de Tela

        txtNome.setText("");
        txtValor.setText("");
        txtQtd.setText("");
        txtID.setText("XXXX");

        txtNome.setEnabled(false);
        txtValor.setEnabled(false);
        txtQtd.setEnabled(false);

        //Controle de Botões
        btnSalva.setEnabled(false);
        btnPesquisa.setEnabled(true);
        btnNovo.setEnabled(true);
        btnCancela.setEnabled(false);
        btnExclui.setEnabled(false);
        btnAltera.setEnabled(false);
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void btnExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiActionPerformed
        CadasProdutoDAO dao = new CadasProdutoDAO();
        int apagado = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (apagado == JOptionPane.YES_OPTION) {
            if (dao.deletar(dao)) {
                JOptionPane.showMessageDialog(this, "Usuário Apagada com sucesso!");
                //Controle de Tela
                txtID.setText("XXXX");
                txtNome.setText("");
                txtValor.setText("");
                txtQtd.setText("");

                txtNome.setEnabled(false);
                txtValor.setEnabled(false);
                txtQtd.setEnabled(false);

                //Controle de Botões
                btnSalva.setEnabled(false);
                btnPesquisa.setEnabled(true);
                btnNovo.setEnabled(true);
                btnCancela.setEnabled(false);
                btnExclui.setEnabled(false);
                btnAltera.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnExcluiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm8_CadasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm8_CadasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm8_CadasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm8_CadasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm8_CadasProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltera;
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnExclui;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtQtd;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
