/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.systec.view;

/**
 *
 * @author Steve Wallef
 */
public class Frm9_Venda extends javax.swing.JFrame {

    /**
     * Creates new form Frm9_Venda
     */
    public Frm9_Venda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtSenha2 = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JPasswordField();
        btnExcluir = new javax.swing.JButton();
        btnPesquisa1 = new javax.swing.JButton();
        btnNovo1 = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnPesquisa = new javax.swing.JButton();
        btnSalva = new javax.swing.JButton();
        btnAltera = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();
        btnExclui = new javax.swing.JButton();
        txtHora = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens Venda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nome");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 50, 37, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Login");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 110, 34, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Senha");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 170, 37, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Confirma Senha");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 220, 110, 20);

        txtNome1.setEnabled(false);
        jPanel2.add(txtNome1);
        txtNome1.setBounds(20, 70, 280, 30);

        txtLogin.setEnabled(false);
        jPanel2.add(txtLogin);
        txtLogin.setBounds(20, 130, 280, 30);

        txtSenha2.setEnabled(false);
        jPanel2.add(txtSenha2);
        txtSenha2.setBounds(20, 240, 280, 30);

        txtSenha.setEnabled(false);
        jPanel2.add(txtSenha);
        txtSenha.setBounds(20, 190, 280, 30);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/iconCancelar.png"))); // NOI18N
        btnExcluir.setToolTipText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(btnExcluir);
        btnExcluir.setBounds(260, 280, 40, 39);

        btnPesquisa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/iconPesquisa.png"))); // NOI18N
        btnPesquisa1.setToolTipText("Pesquisa");
        btnPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisa1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnPesquisa1);
        btnPesquisa1.setBounds(60, 280, 40, 40);

        btnNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/iconAdicionar.png"))); // NOI18N
        btnNovo1.setToolTipText("Novo ");
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNovo1);
        btnNovo1.setBounds(10, 280, 40, 40);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/iconOk.png"))); // NOI18N
        btnSalvar.setToolTipText("Salva ");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);
        btnSalvar.setBounds(110, 280, 40, 39);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/iconMenos.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);
        btnCancelar.setBounds(160, 280, 40, 39);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/iconEditar.png"))); // NOI18N
        btnAlterar.setToolTipText("Altera");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlterar);
        btnAlterar.setBounds(210, 280, 40, 39);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 380, 500, 330);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Venda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("ID");

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.setText("XXXX");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cliente");

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setEnabled(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Hora");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Data ");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Plus_50px.png"))); // NOI18N
        btnNovo.setToolTipText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Search_Property_50px.png"))); // NOI18N
        btnPesquisa.setToolTipText("Pesquisa");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        btnSalva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Ok_50px.png"))); // NOI18N
        btnSalva.setToolTipText("Salva");
        btnSalva.setEnabled(false);
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        btnAltera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/iconEditar.png"))); // NOI18N
        btnAltera.setToolTipText("Altera");
        btnAltera.setEnabled(false);
        btnAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlteraActionPerformed(evt);
            }
        });

        btnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Minus_50px.png"))); // NOI18N
        btnCancela.setToolTipText("Cancela");
        btnCancela.setEnabled(false);
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });

        btnExclui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/systec/imagens/icons8_Cancel_50px.png"))); // NOI18N
        btnExclui.setToolTipText("Exclui");
        btnExclui.setEnabled(false);
        btnExclui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiActionPerformed(evt);
            }
        });

        try {
            txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHora.setEnabled(false);
        txtHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("jButton1");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setText("XXX");

        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)
                        .addGap(22, 22, 22)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnAltera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnExclui, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtID))
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1)))
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAltera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancela, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExclui, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        //Controle de Tela
        txtNome.setEnabled(true);
        txtValor.setEnabled(true);
        txtHora.setEnabled(true);

        //Controle de Botões
        btnSalva.setEnabled(true);
        btnPesquisa.setEnabled(false);
        btnNovo.setEnabled(false);
        btnAltera.setEnabled(false);
        btnCancela.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        CadasProduto usu = new CadasProduto();
        CadasProdutoDAO cli = new CadasProdutoDAO();
        flang = 2;
        //Chamando tela para realização da pesquisa.
        Frm7_PesqProduto pesqProd = new Frm7_PesqProduto(null, true);
        pesqProd.setVisible(true);

        if (linha >= 0) {

            btnExclui.setEnabled(true);

            cli.pesquisar(CadasProdutoDAO.getId_produtos());

            //Controle de Tela
            txtNome.setEnabled(true);
            txtValor.setEnabled(true);
            txtHora.setEnabled(true);

            //Controle de Botões
            btnSalva.setEnabled(false);
            btnPesquisa.setEnabled(false);
            btnNovo.setEnabled(false);
            btnCancela.setEnabled(true);
            btnAltera.setEnabled(true);

            // Setando campos com seus respectivos valores.
            txtID.setText(Integer.toString(CadasProduto.getId_produtos()));
            txtNome.setText((CadasProduto.getNome()));
            txtValor.setText((CadasProduto.getValor()));
            txtHora.setText((CadasProduto.getQtd()));

        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed

        if (!txtNome.getText().isEmpty() && !txtValor.getText().equals("  .  ") && !txtHora.equals("  .  ")) {

            CadasProdutoDAO pro = new CadasProdutoDAO();
            CadasProduto cad = new CadasProduto(txtNome.getText(),txtValor.getText(),txtHora.getText());
            int salva = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja salvar?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (salva == JOptionPane.YES_OPTION) {
                if (pro.inserir(cad)) {
                    JOptionPane.showMessageDialog(this, "Produto Salvo com sucesso!");

                    //Controle de Tela
                    txtNome.setText("");
                    txtValor.setText("");
                    txtHora.setText("");

                    txtNome.setEnabled(false);
                    txtValor.setEnabled(false);
                    txtHora.setEnabled(false);

                    //Controle de Botões
                    btnSalva.setEnabled(false);
                    btnPesquisa.setEnabled(true);
                    btnCancela.setEnabled(false);
                    btnNovo.setEnabled(true);
                    btnAltera.setEnabled(false);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Por Favor Preencha Todos os Campos");
            }
        }
    }//GEN-LAST:event_btnSalvaActionPerformed

    private void btnAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlteraActionPerformed

        CadasProdutoDAO dao = new CadasProdutoDAO();
        CadasProduto cad = new CadasProduto(Integer.parseInt(txtID.getText()), txtNome.getText(), txtValor.getText(), txtHora.getText());
        int altera = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja alterar?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (altera == JOptionPane.YES_OPTION) {
            if (dao.alterar(cad)) {
                JOptionPane.showMessageDialog(this, "Alteração de Produto Salva com sucesso!");

                //Controle de Tela
                txtID.setText("XXXX");
                txtNome.setText("");
                txtValor.setText("");
                txtHora.setText("");

                txtNome.setEnabled(false);
                txtValor.setEnabled(false);
                txtHora.setEnabled(false);

                //Controle de Botões
                btnSalva.setEnabled(false);
                btnPesquisa.setEnabled(true);
                btnNovo.setEnabled(true);
                btnAltera.setEnabled(false);
                btnExclui.setEnabled(false);
                btnCancela.setEnabled(false);
            }

        }
    }//GEN-LAST:event_btnAlteraActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        //Controle de Tela

        txtNome.setText("");
        txtValor.setText("");
        txtHora.setText("");
        txtID.setText("XXXX");

        txtNome.setEnabled(false);
        txtValor.setEnabled(false);
        txtHora.setEnabled(false);

        //Controle de Botões
        btnSalva.setEnabled(false);
        btnPesquisa.setEnabled(true);
        btnNovo.setEnabled(true);
        btnCancela.setEnabled(false);
        btnExclui.setEnabled(false);
        btnAltera.setEnabled(false);
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void btnExcluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiActionPerformed
        CadasProdutoDAO dao = new CadasProdutoDAO();
        int apagado = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (apagado == JOptionPane.YES_OPTION) {
            if (dao.deletar(dao)) {
                JOptionPane.showMessageDialog(this, "Usuário Apagada com sucesso!");
                //Controle de Tela
                txtID.setText("XXXX");
                txtNome.setText("");
                txtValor.setText("");
                txtHora.setText("");

                txtNome.setEnabled(false);
                txtValor.setEnabled(false);
                txtHora.setEnabled(false);

                //Controle de Botões
                btnSalva.setEnabled(false);
                btnPesquisa.setEnabled(true);
                btnNovo.setEnabled(true);
                btnCancela.setEnabled(false);
                btnExclui.setEnabled(false);
                btnAltera.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnExcluiActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        CadasUsuarioDAO dao = new CadasUsuarioDAO();
        int apagado = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (apagado == JOptionPane.YES_OPTION) {
            if (dao.deletar(dao)) {
                JOptionPane.showMessageDialog(this, "Usuário Apagada com sucesso!");
                //Controle de Tela
                txtID.setText("");
                txtNome.setText("");
                txtLogin.setText("");
                txtSenha.setText("");
                txtSenha2.setText("");

                txtNome.setEnabled(false);
                txtLogin.setEnabled(false);
                txtSenha.setEnabled(false);
                txtSenha2.setEnabled(false);

                //Controle de Botões
                btnSalvar.setEnabled(false);
                btnPesquisa.setEnabled(true);
                btnNovo.setEnabled(true);
                btnCancelar.setEnabled(false);
                btnExcluir.setEnabled(false);
                btnAlterar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisa1ActionPerformed
        CadasUsuario usu = new CadasUsuario();
        CadasUsuarioDAO cad = new CadasUsuarioDAO();

        //Chamando tela para realização da pesquisa.
        Frm4_PesqUsuario pesqUsu = new Frm4_PesqUsuario(null, true);
        pesqUsu.setVisible(true);

        if (linha >= 0) {

            btnExcluir.setEnabled(true);

            cad.pesquisar(CadasUsuarioDAO.getId_usuario());

            //Controle de Tela
            txtNome.setEnabled(true);
            txtLogin.setEnabled(true);
            txtSenha.setEnabled(true);
            txtSenha2.setEnabled(true);

            //Controle de Botões
            btnSalvar.setEnabled(false);
            btnPesquisa.setEnabled(false);
            btnNovo.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnCancelar.setEnabled(true);

            // Setando campos com seus respectivos valores.
            txtID.setText(Integer.toString(usu.getId_usuario()));
            txtNome.setText((usu.getNome()));
            txtLogin.setText((usu.getLogin()));
            txtSenha.setText((usu.getSenha()));
            txtSenha2.setText((usu.getSenha()));

        }
    }//GEN-LAST:event_btnPesquisa1ActionPerformed

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        //Controle de Tela
        txtNome.setEnabled(true);
        txtLogin.setEnabled(true);
        txtSenha.setEnabled(true);
        txtSenha2.setEnabled(true);

        //Controle de Botões
        btnSalvar.setEnabled(true);
        btnPesquisa.setEnabled(false);
        btnNovo.setEnabled(false);
        btnCancelar.setEnabled(true);
    }//GEN-LAST:event_btnNovo1ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!txtNome.getText().isEmpty() && !txtLogin.getText().isEmpty() && !txtSenha.getText().isEmpty() && !txtSenha2.getText().isEmpty()) {
            if (!txtSenha.getText().equals(txtSenha2.getText())) {

                JOptionPane.showMessageDialog(this, "Senhas Iválidas......");

            } else {

                CadasUsuarioDAO cad = new CadasUsuarioDAO();
                CadasUsuario usu = new CadasUsuario(txtNome.getText(), txtLogin.getText(), txtSenha.getText());
                int salva = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja salvar?", "Atenção", JOptionPane.YES_NO_OPTION);
                if (salva == JOptionPane.YES_OPTION) {
                    if (cad.inserir(usu)) {
                        JOptionPane.showMessageDialog(this, "Usuário Salvo com sucesso!");

                        //Controle de Tela
                        txtNome.setText("");
                        txtLogin.setText("");
                        txtSenha.setText("");
                        txtSenha2.setText("");

                        txtNome.setEnabled(false);
                        txtLogin.setEnabled(false);
                        txtSenha.setEnabled(false);
                        txtSenha2.setEnabled(false);

                        //Controle de Botões
                        btnSalvar.setEnabled(false);
                        btnPesquisa.setEnabled(true);
                        btnNovo.setEnabled(true);
                        btnCancelar.setEnabled(false);

                    }

                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por Favor Preencha Todos os Campos");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //Controle de Tela

        txtNome.setText("");
        txtLogin.setText("");
        txtSenha.setText("");
        txtSenha2.setText("");
        txtID.setText("");

        txtNome.setEnabled(false);
        txtLogin.setEnabled(false);
        txtSenha.setEnabled(false);
        txtSenha2.setEnabled(false);

        //Controle de Botões
        btnSalvar.setEnabled(false);
        btnPesquisa.setEnabled(true);
        btnNovo.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (!txtSenha.getText().equals(txtSenha2.getText())) {

            JOptionPane.showMessageDialog(this, "Senhas Iválidas......");

        } else {
            CadasUsuarioDAO dao = new CadasUsuarioDAO();
            CadasUsuario cad = new CadasUsuario(Integer.parseInt(txtID.getText()), txtNome.getText(), txtLogin.getText(), txtSenha.getText());
            int altera = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja alterar?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (altera == JOptionPane.YES_OPTION) {
                if (dao.alterar(cad)) {
                    JOptionPane.showMessageDialog(this, "Alteração de Usuário Salva com sucesso!");

                    //Controle de Tela
                    txtID.setText("");
                    txtNome.setText("");
                    txtLogin.setText("");
                    txtSenha.setText("");
                    txtSenha2.setText("");

                    txtNome.setEnabled(false);
                    txtLogin.setEnabled(false);
                    txtSenha.setEnabled(false);
                    txtSenha2.setEnabled(false);

                    //Controle de Botões
                    btnSalvar.setEnabled(false);
                    btnPesquisa.setEnabled(true);
                    btnNovo.setEnabled(true);
                    btnCancelar.setEnabled(false);
                    btnExcluir.setEnabled(false);
                    btnAlterar.setEnabled(false);
                }
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm9_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm9_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm9_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm9_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm9_Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltera;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExclui;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnPesquisa1;
    private javax.swing.JButton btnSalva;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenha2;
    // End of variables declaration//GEN-END:variables
}
